import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import crypto from 'crypto'
import { generateOTP, hashOTP } from '@vaultprint/lib'

// ---------------------------------------------------------------------------
// POST /api/webhooks/razorpay
//
// Razorpay server-to-server webhook. Verifies X-Razorpay-Signature header
// using the webhook secret (different from key_secret).
//
// Idempotent: checks if job already has status >= paid before updating.
// Performs the same OTP generation as /payment/verify.
// ---------------------------------------------------------------------------

function getAdminSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_KEY!,
    { auth: { persistSession: false, autoRefreshToken: false } }
  )
}

export async function POST(request: NextRequest) {
  const signature = request.headers.get('x-razorpay-signature')
  if (!signature) {
    return NextResponse.json({ error: 'Missing signature' }, { status: 401 })
  }

  const webhookSecret = process.env.RAZORPAY_WEBHOOK_SECRET
  if (!webhookSecret) {
    console.error('RAZORPAY_WEBHOOK_SECRET not configured')
    return NextResponse.json({ error: 'Webhook not configured' }, { status: 500 })
  }

  // Read raw body for signature verification
  const rawBody = await request.text()

  // Verify webhook signature
  const expectedSignature = crypto
    .createHmac('sha256', webhookSecret)
    .update(rawBody)
    .digest('hex')

  const isValid = crypto.timingSafeEqual(
    Buffer.from(signature),
    Buffer.from(expectedSignature)
  )

  if (!isValid) {
    return NextResponse.json({ error: 'Invalid signature' }, { status: 401 })
  }

  // Parse the webhook payload
  let payload: any
  try {
    payload = JSON.parse(rawBody)
  } catch {
    return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 })
  }

  // We only care about payment.captured events
  if (payload.event !== 'payment.captured') {
    return NextResponse.json({ ok: true, skipped: true })
  }

  const payment = payload.payload?.payment?.entity
  if (!payment) {
    return NextResponse.json({ error: 'No payment entity in payload' }, { status: 400 })
  }

  const orderId = payment.order_id
  const paymentId = payment.id

  if (!orderId || !paymentId) {
    return NextResponse.json({ error: 'Missing order_id or payment_id' }, { status: 400 })
  }

  const supabase = getAdminSupabase()

  // Find job by razorpay_order_id
  const { data: job, error: jobError } = await supabase
    .from('print_jobs')
    .select('id, status')
    .eq('razorpay_order_id', orderId)
    .single()

  if (jobError || !job) {
    console.error('Webhook: job not found for order', orderId)
    // Return 200 to prevent Razorpay from retrying
    return NextResponse.json({ ok: true, skipped: true, reason: 'job_not_found' })
  }

  // Idempotent: if already processed, skip
  const processedStatuses = ['paid', 'queued', 'printing', 'completed', 'failed']
  if (processedStatuses.includes(job.status)) {
    return NextResponse.json({ ok: true, skipped: true, reason: 'already_processed' })
  }

  // Generate OTP (same logic as /verify)
  const otp = generateOTP()
  const otpHash = await hashOTP(otp)
  const expiresAt = new Date(Date.now() + 15 * 60 * 1000).toISOString()

  // Update job
  const { error: updateError } = await supabase
    .from('print_jobs')
    .update({
      razorpay_payment_id: paymentId,
      otp_hash: otpHash,
      otp_expires_at: expiresAt,
      otp_attempts: 0,
      status: 'queued',
    })
    .eq('id', job.id)

  if (updateError) {
    console.error('Webhook: failed to update job:', updateError)
    return NextResponse.json({ error: 'Update failed' }, { status: 500 })
  }

  // Audit log
  await supabase.from('audit_log').insert({
    job_id: job.id,
    event: 'payment_verified',
    actor: 'webhook',
    metadata: { razorpay_order_id: orderId, razorpay_payment_id: paymentId },
  })

  await supabase.from('audit_log').insert({
    job_id: job.id,
    event: 'otp_generated',
    actor: 'webhook',
    metadata: { expires_at: expiresAt },
  })

  // Note: OTP generated by webhook cannot be shown to user.
  // The /verify endpoint is the primary path. Webhook is the fallback.
  return NextResponse.json({ ok: true })
}
