import type { Metadata } from "next";
import { Ponnala, Plus_Jakarta_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const ponnala = Ponnala({
  weight: "400",
  variable: "--font-ponnala",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-jakarta",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ponnala.variable} ${jakarta.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased font-ponnala`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
