'use client'

import { Suspense } from 'react'
import { useParams, useRouter, useSearchParams } from 'next/navigation'

// ---------------------------------------------------------------------------
// /kiosk/[kioskId]/mode2/otp — only rendered for otp_display: "show" clients.
//
// Displays the OTP generated by pos-confirm, then hands off to the
// existing (unmodified) enter-otp screen. Default clients skip this
// screen entirely (PRD C2.5).
// ---------------------------------------------------------------------------

function Mode2OtpInner() {
  const params = useParams<{ kioskId: string }>()
  const search = useSearchParams()
  const router = useRouter()
  const kioskId = params.kioskId
  const otp = search.get('otp') ?? ''

  return (
    <div className="flex w-full max-w-[440px] flex-col items-center gap-6 text-center">
      <div>
        <h2 className="text-xl lg:text-2xl font-bold text-white tracking-wide">Your print code</h2>
        <p className="mt-1 text-sm text-zinc-400">Enter this code on the next screen to release your print</p>
      </div>

      <div className="flex items-center justify-center gap-2">
        {otp.split('').map((digit, i) => (
          <div
            key={i}
            className="flex h-16 w-12 items-center justify-center rounded-xl border-2 border-teal-400 bg-teal-400/10 shadow-[0_0_10px_rgba(45,212,191,0.2)]"
          >
            <span className="font-jakarta text-3xl font-bold text-white">{digit}</span>
          </div>
        ))}
      </div>

      <button
        onClick={() => router.push(`/kiosk/${kioskId}/enter-otp`)}
        className="w-full rounded-2xl bg-teal-500 px-6 py-4 text-lg font-bold text-teal-950 shadow-[0_0_20px_rgba(45,212,191,0.35)] transition hover:bg-teal-400 active:scale-[0.99]"
      >
        Continue — enter the code
      </button>
    </div>
  )
}

export default function Mode2OtpPage() {
  return (
    <Suspense fallback={null}>
      <Mode2OtpInner />
    </Suspense>
  )
}
