-- ─── 003_rls.sql ───────────────────────────────────────────────────────────
-- Row Level Security (RLS) policies for VaultPrint tables.
-- 
-- The application relies heavily on the service_role key for backend API operations
-- (which bypasses RLS), but for direct client access (like the mobile app fetching
-- its own print job or the kiosk app subscribing to its own jobs via Realtime),
-- we need appropriate RLS policies.
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Enable RLS on all tables
ALTER TABLE kiosks ENABLE ROW LEVEL SECURITY;
ALTER TABLE pricing_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE print_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;

-- 2. Kiosks table
-- Kiosks are public to read (for the /start page to check offline status).
-- Write/Update is restricted to service_role (Admin API).
CREATE POLICY "Kiosks are readable by everyone" ON kiosks
    FOR SELECT USING (true);

-- 3. Pricing Config table
-- Pricing is public to read. Write restricted to service_role.
CREATE POLICY "Pricing config is readable by everyone" ON pricing_config
    FOR SELECT USING (true);

-- 4. Print Jobs table
-- Users should be able to read their own job by session_id.
-- Kiosks should be able to read their own queued jobs via Realtime.
-- Since we don't have user authentication in the mobile app (anonymous sessions),
-- we allow reading print_jobs. The security is enforced by the unguessable session_id UUID.
-- We also allow inserting a new print job.
CREATE POLICY "Print jobs are readable by anyone" ON print_jobs
    FOR SELECT USING (true);

CREATE POLICY "Anyone can create a print job" ON print_jobs
    FOR INSERT WITH CHECK (true);

-- We explicitly do NOT allow UPDATE or DELETE via client APIs.
-- Updates must go through our backend Next.js API routes (which use service_role).

-- 5. Audit Log table
-- Reads are strictly backend-only (no SELECT policy — service_role only).
-- INSERT is allowed because the mobile /start page logs 'session_created'
-- with the anon key (matches current app behavior; without this policy that
-- audit event would be silently dropped).
CREATE POLICY "Anyone can insert audit events" ON audit_log
    FOR INSERT WITH CHECK (true);

-- 6. Storage Bucket Policies (print-files)
-- Users can upload files to the print-files bucket.
-- Reading files is restricted (agent uses a pre-signed URL generated by backend).
CREATE POLICY "Anyone can upload print files" ON storage.objects
    FOR INSERT WITH CHECK ( bucket_id = 'print-files' );

-- Note: No SELECT policy for storage.objects on 'print-files'.
-- This ensures files cannot be downloaded publicly.
